### PR TITLE
Dana's suggested changes

### PR DESCRIPTION
**Pull request by D-Bits**

### CODE REVIEW

**Comment by anuslorah** [comment]
merged all pull requests to distill information in a different environment -- the web interface crashes when I attempt to move larger chunks of text more than once.

**Comment by D-Bits** [comment]
Understood. I hope my contributions were valuable

________________________________

**Comment by anuslorah** [comment]
Excellent contribution, I think having a glossary is great. I just cut the words down a bit due to space (also, I am an editor, my last time in college was spent purely on studying editing)


--Anu


________________________________

**Comment by D-Bits** [comment]
Understood. I'll see if I can come up with any web GUI guides.

________________________________

**Comment by D-Bits** [comment]
Hey, are we all suppose to be collaborating on this too? https://canvas.seattlecentral.edu/courses/1411136/assignments/9072292

________________________________

**Pull request merged**
